### ISSUE TITLE
能加套格式化规则吗

### ISSUE THREAD

**Issue by weiShaoY** [Flower-guest/projectBuildTemplate#1]
大佬能否把eslint规则优化下,另外,这个用的应该是eslint格式化吧,但经常性失效,
能否根据这个项目配套prettier规则

eslint 我在此基础上加了以下内容
 "padding-line-between-statements": [
      "error",
      {
        blankLine: "always",
        prev: "*",
        next: "function",
      }, // 函数前填充空行
      {
        blankLine: "always",
        prev: "*",
        next: "export",
      }, // export前填充空行
      {
        blankLine: "always",
        prev: "*",
        next: "block",
      }, // {} 前换行
      {
        blankLine: "always",
        prev: "*",
        next: "block-like",
      }, // {} 前换行
      {
        blankLine: "always",
        prev: "*",
        next: "expression",
      },
      {
        blankLine: "always",
        prev: "*",
        next: "multiline-block-like",
      }, // 多类{}前填充空行
      {
        blankLine: "always",
        prev: "multiline-let",
        next: "*",
      }, // 多个let后空行
      {
        blankLine: "always",
        prev: "multiline-const",
        next: "*",
      }, // 多个cont后空行
      {
        blankLine: "always",
        prev: "const",
        next: "*",
      }, // 多个cont后空行
      {
        blankLine: "always",
        prev: "import",
        next: "*",
      }, // 每个import后空行
    ],
    "no-multiple-empty-lines": [1, { max: 1 }], // 空行最多不能超过3行

    "vue/html-closing-bracket-newline": "off",

    "no-template-shadow": "off",

    "vue/html-self-closing": "off",

**Comment by Flower-guest** [comment]
hi，你好很高兴你提的建议，我后续添加一下，是使用eslint格式化，后续考虑结合eslint+prettier规则,谢谢你的建议
